### ISSUE TITLE
code release date ?

### ISSUE THREAD

**Issue by huawei-sai** [OpenRobotLab/Grounded_3D-LLM#1]
When will the code be made open-source ?

**Comment by chenyilun95** [comment]
Hi, thanks for your interest! We’re reorganizing the code and will release it in a few weeks.

**Comment by huawei-sai** [comment]
thank you so much and looking forward to it

**Comment by SergioArnaud** [comment]
Great work @chenyilun95! Any update on the release date?

**Comment by chenyilun95** [comment]
Thank you for your attention. We plan to release both the training setup and the pretrained CLASP model this weekend. The overall training with LLM is currently being organized and will be available shortly.
