### ISSUE TITLE
ScanNet Download

### ISSUE THREAD

**Issue by SeanChenxy** [OpenRobotLab/Grounded_3D-LLM#2]
Hi, Thanks for sharing the codes. The ScanNet is 1.2TB in size. It is hard to download the whole dataset. Is there any way to reduce the download size?

**Comment by YangS03** [comment]
We are gradually releasing our data. The processed ScanNet(~7G) can be accessed at: https://huggingface.co/datasets/ShuaiYang03/Grounded_3D_LLM_with_Referent_Tokens_Dataset

**Comment by SeanChenxy** [comment]
If the processed ScanNet(7G) is obtained, do we still need raw ScanNet? I found the `rawscannet` is still necessary in data visualization:

```
python visualize_grounded_text.py --datapath ../data/rawscannet/ ...
```

**Comment by YangS03** [comment]
The script has been updated. Please follow the new instructions provided in the README.

**Comment by yun189** [comment]
please ，where is newest readme ?

**Comment by YangS03** [comment]
I've now updated both the README files: the one in the [data_visualization](https://github.com/OpenRobotLab/Grounded_3D-LLM/tree/master/data_visualization) directory and the one at the root path.

**Comment by SeanChenxy** [comment]
Hi, I have run 
`python visualize_grounded_text.py --datapath ../data/processed/scannet200 ...`
but get
`No such file or directory: '../data/processed/scannet200/scans/scene0000_00/scene0000_00_vh_clean_2.ply`

**Comment by YangS03** [comment]
Could you please check if you have pulled the latest code?

**Comment by SeanChenxy** [comment]
Thanks for your reminder. I have run it.
