### ISSUE TITLE
Great work @chenyilun95! Could you perhaps provide a more detailed explanation of how the input and output of the LLM are constructed?

### ISSUE THREAD

**Issue by DevXiaoYan** [OpenRobotLab/Grounded_3D-LLM#4]

**Comment by chenyilun95** [comment]
Hi, thank you for your interest! For each specific task, please refer to the task-specific instruction generation templates in Section G, which generate instructions based on existing language data. Additionally, you can find the step-by-step process for generating the grounded scene caption dataset in Section 3.3.
