### ISSUE TITLE
Ask for the object caption in the step 1

### ISSUE THREAD

**Issue by WeitaiKang** [OpenRobotLab/Grounded_3D-LLM#7]
Dear authors,

Thanks for your great job! Could you further release the object captions generated by CogVLM in your first step?

**Comment by ZzZZCHS** [comment]
Hi, thank you for your interest!

We’ve previously released object captions, which you can access [here](https://huggingface.co/datasets/ShuaiYang03/Grounded_3D_LLM_with_Referent_Tokens_Dataset/tree/main/raw_langdata).

**Comment by WeitaiKang** [comment]
Great! Thank you.
