### ISSUE TITLE
Ask for performance on ScanQA(val)@M and @R

### ISSUE THREAD

**Issue by WeitaiKang** [OpenRobotLab/Grounded_3D-LLM#8]
Hi authors,

Thanks for you great job! I notice that you have evaluate on ScanQA(val)  on BLEU and Cider. Could you further provide the performance on METEOR and ROUGE? Many related works have conduct those experiments. And I think it would improve your impact when others wanna cite your paper to compare on these metric.

Look forward to your response!

**Comment by chenyilun95** [comment]
Thank you for your interest in our work!

We have just released the model checkpoints. For reference, the model achieves the following performance metrics: CIDEr 75.9, BLEU-4 13.3, METEOR 15.2, and ROUGE-L 37.1.

**Comment by WeitaiKang** [comment]
Thanks for your response!
